<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Aspire1698" name="com.sheplers.testscripts.myaccount.OrderHistory" tests="17" failures="1" timestamp="28 Jul 2017 23:49:50 GMT" time="1716.828" errors="1">
  <testcase name="TC_SHEPLERS_OH_011" time="15.603" classname="com.sheplers.testscripts.myaccount.OrderHistory"/>
  <testcase name="TC_SHEPLERS_OH_010" time="156.860" classname="com.sheplers.testscripts.myaccount.OrderHistory"/>
  <testcase name="TC_SHEPLERS_OH_014" time="44.108" classname="com.sheplers.testscripts.myaccount.OrderHistory"/>
  <testcase name="TC_SHEPLERS_OH_008" time="142.231" classname="com.sheplers.testscripts.myaccount.OrderHistory"/>
  <testcase name="TC_SHEPLERS_OH_003" time="158.562" classname="com.sheplers.testscripts.myaccount.OrderHistory"/>
  <testcase name="TC_SHEPLERS_OH_013" time="23.530" classname="com.sheplers.testscripts.myaccount.OrderHistory"/>
  <testcase name="TC_SHEPLERS_OH_004" time="143.426" classname="com.sheplers.testscripts.myaccount.OrderHistory"/>
  <testcase name="TC_SHEPLERS_OH_017" time="148.927" classname="com.sheplers.testscripts.myaccount.OrderHistory"/>
  <testcase name="TC_SHEPLERS_OH_015" time="18.903" classname="com.sheplers.testscripts.myaccount.OrderHistory"/>
  <testcase name="TC_SHEPLERS_OH_002" time="31.313" classname="com.sheplers.testscripts.myaccount.OrderHistory"/>
  <testcase name="TC_SHEPLERS_OH_001" time="140.360" classname="com.sheplers.testscripts.myaccount.OrderHistory"/>
  <testcase name="TC_SHEPLERS_OH_012" time="134.594" classname="com.sheplers.testscripts.myaccount.OrderHistory">
    <error type="java.lang.ArrayIndexOutOfBoundsException" message="2">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 2
	at com.sheplers.reusablecomponents.AccountUtils.doAccountOperations(AccountUtils.java:78)
	at com.sheplers.pages.headers.OrderStatusPage.enterOrderStatusDetail(OrderStatusPage.java:182)
	at com.sheplers.testscripts.myaccount.OrderHistory.TC_SHEPLERS_OH_012(OrderHistory.java:2965)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- TC_SHEPLERS_OH_012 -->
  <testcase name="TC_SHEPLERS_OH_005" time="175.009" classname="com.sheplers.testscripts.myaccount.OrderHistory"/>
  <testcase name="TC_SHEPLERS_OH_007" time="173.594" classname="com.sheplers.testscripts.myaccount.OrderHistory">
    <failure type="java.lang.AssertionError" message="44. Order number is not matched with OMS number, plz check the log event">
      <![CDATA[java.lang.AssertionError: 44. Order number is not matched with OMS number, plz check the log event
	at org.testng.Assert.fail(Assert.java:93)
	at com.sheplers.support.Log.fail(Log.java:529)
	at com.sheplers.support.Log.assertThat(Log.java:669)
	at com.sheplers.testscripts.myaccount.OrderHistory.TC_SHEPLERS_OH_007(OrderHistory.java:1731)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- TC_SHEPLERS_OH_007 -->
  <testcase name="TC_SHEPLERS_OH_006" time="44.296" classname="com.sheplers.testscripts.myaccount.OrderHistory"/>
  <testcase name="TC_SHEPLERS_OH_009" time="147.979" classname="com.sheplers.testscripts.myaccount.OrderHistory"/>
  <testcase name="TC_SHEPLERS_OH_016" time="17.533" classname="com.sheplers.testscripts.myaccount.OrderHistory"/>
</testsuite> <!-- com.sheplers.testscripts.myaccount.OrderHistory -->
